### ISSUE TITLE
Issue with areas in the blockgrid(gridView.html)

### ISSUE THREAD

**Issue by jeroenVanKempenIo** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#7]
Hello,

I have installed your package and was checking it out with the demo block provided by Umbraco. But when I wanted to add the block "Two Column Layout" it does not show up correctly. It only shows a blank row and no possibility of adding blocks underneath. Is there an different function I have to implement like with Umbraco.Community.BlockPreview or something else I’m missing?

Package version: 1.0.6
Umbraco Version: 13.4.0

**Comment by kasparboelkjeldsen** [comment]
I think the best scenario with column elements like that is to just not set a custom view for them 

This is where I've set gridView.html for all the elements except twoColumn. It is not really possible for me to expose the same functionality they create with the demo grid.

![image](https://github.com/user-attachments/assets/2c3b7988-9d04-49b8-82d9-9397ade8cc2a)

For reference, this is the custom view included in the demo grid

```html
<section ng-style="{'background-color': block.data.backgroundColor}">
    <umb-block-grid-render-area-slots></umb-block-grid-render-area-slots>
</section>
```

and this is the source code for the cshtml view

```razor
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>

<div>
    @await Html.GetBlockGridItemAreasHtmlAsync(Model)
</div>
```

I'd have to do some nasty "detect the GetBlockGridItemAreasHtmlAsync" and try to add a slot in angular, which might have all kinds of side-effects, and I believe the end result is close enough with just not setting a custom view at all (like in the above screenshot)

**Comment by jeroenVanKempenIo** [comment]
Thanks for the responce, I have tried it this way and is what i am looking for thank you.

**Comment by kasparboelkjeldsen** [comment]
Glad that helped. It's an interesting "problem" though. Say someone has an area that has a bunch of other stuff attached to it than "just" @await Html.GetBlockGridItemAreasHtmlAsync(Model). We should be able to show that too.

I think I have a solution for it, but as mentioned I'll gate it behind a configuration set to true, because it might have side effects.

I'm working with adding "AreaReplace": true to the config
This will allow you to do this

@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>

```razor
<div>
    This is my 2-col<hr />
    @await Html.GetBlockGridItemAreasHtmlAsync(Model)
    @ViewBag.renderGridAreaSlots
</div>
```

Bit of "magic", but using a viewBag value here is safe, as it will be empty on a normal render and therefore not output anything, but populated when we render through the API, allowing me to swap in the area angular-stuff at that position in the backoffice.

**Comment by kasparboelkjeldsen** [comment]
I've released v 1.0.7 and 2.0.10 that supports this behavior :)

**Comment by jeroenVanKempenIo** [comment]
I only see the text "renderGridAreaSlots" and in my console get the error "Cannot read properties of null (reading 'firstElementChild')"

**Comment by kasparboelkjeldsen** [comment]
@jeroenVanKempenIo I'm thinking that must be a caching issue ? What does the code in the gridView.html look like?

It should contain 

<div class="custom-block" style="cursor:pointer" block-type="grid" ng-controller="customBlockController">

    <style>
        #contentDiv {
            overflow: hidden;
        }
    </style>
    <div id="contentDiv" ng-attr-ng-click="enableBlockEdit && block.edit()" execute-scripts="html" ng-cloak>Loading...</div>
    <div id="areaDiv" style="display:none">
        <umb-block-grid-render-area-slots></umb-block-grid-render-area-slots>
    </div>
</div>


for everything to work

**Comment by jeroenVanKempenIo** [comment]
It was indeed an cashing issue in incognito it work
